riftLevels: "Разлом забрал у вас 2 уровня"

newOreChance: "<#DB7093>ʟᴇᴠᴇʟ ᴜᴘ!</#DB7093> <white>теперь ваш шанс добыть больше руды:</white> <#DB7093><newCoef></#DB7093>"
newWoodChance: "<#DB7093>ʟᴇᴠᴇʟ ᴜᴘ!</#DB7093> <white>теперь ваш шанс добыть больше дерева:</white> <#DB7093><newCoef></#DB7093>"

acceptingTicket: "Твоя заявка была одобрена! Приятной игры! `<player>`"
tryingToLogIn: "Вы пытаетесь войти на сервер?"

guildId: "1388842817027309639"
roleToAdd: "1472957151667421204"
roleToRemove: "1472957117735506030"

logsChannel: "1472943741366173787"
ticketChannelId: "1472697699663872120"

errorHasNotJoinedYet: "Игрок ещё не заходил на сервер"
errorNoPermission: "У тебя нету прав на выполнение этого действия"

emojiDisc1: "<:disc3:1473702070312894474>"
emojiDisc2: "<:disc2:1473702351326937352>"
emojiDisc3: "<:disc1:1473702369845055699>"
emojiDisc4: "<:disc4:1473703235196813356>"

event30min: "Ивент начнётся через 30 минут!"
event15min: "Ивент начнётся через 15 минут!"
eventNow: "<player> был избран в качестве цели, убейте его до <timeForEvent>"

eventDeath: "<player> получает награду!"
eventQuit: "<player> вышел из игры, ивент перезапущен!"
eventEnd: "Ивент завершён"

activeInEvent: "Теперь вы учавствуете в ивенте"
inactiveInEvent: "Теперь вы не учавствуете в ивенте"
nobodyIsActiveInEvent: "Никто не учавсвтует в ивенте, он не был запущен.."

flowersCollecting: "Вы успешно собрали цветок! Сейчас у вас <count> из 13 цветков!"
diamondCollecting: "Вы успешно собрали алмаз! Сейчас у вас <count> из 20 алмазов!"
striderMessage: "Вы успешно прокатились на страйдере 30 секунд!"
sheepMessage: "Вы успешно покрасили овцу! Сейчас у вас <count> из 7 овец!"
actionBar: "Сейчас цель на координатах <x> <z>"

flowers: "Выпал ивент цветы! Сломай 13 различных цветов!"
diamonds: "Выпал ивент алмазная руда! Сломай 20 блоков алмазной руды!"
striders: "Выпал ивент страйдер! Прокатись на страйдере!"
sheeps: "Выпал ивент овцы! Покрась 7 разных овец в разные цвета!"

eventWonByTarget: "Вы выиграли поздравляем! На ваш баланс зачислено 150 звёздочек и вам выдано 15 АР!"

itemInLeftHand: "Во время выполнения задания в левой руке у вас должен быть <offHand>"